easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
                fields: ['id', 'email', 'firstname', 'lastname']
            edit:
                fields:
                    - email
                    - pseudo
                    - firstname
                    - lastname
                    - accounts
                    - transactions
                    - friendships
                    - friendsIveAsked
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            disabled_actions: ['new']
        Category:
            class: App\Entity\Category
        Account:
            class: App\Entity\Account
        Transaction:
            class: App\Entity\Transaction

