version: '3.7'

services:

  composer:
    container_name: ${DOCKER_PREFIX}composer
    restart: "no"
    build: ./docker/composer
    volumes:
      - .:/app
    command: install

  db:
    container_name: ${DOCKER_PREFIX}postgres
    build: ./docker/postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_database:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  nginx:
    container_name: ${DOCKER_PREFIX}nginx
    build: ./docker/nginx
    ports:
      - ${APP_PORT}:80
    volumes:
      - './:/usr/share/nginx/html'
    depends_on:
      - db
      - php

  php:
    container_name: ${DOCKER_PREFIX}php
    build: ./docker/php
    volumes:
      - './:/usr/share/nginx/html'


volumes:
    postgres_database:
        external: true
